openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple blog API.
  contact:
    name: Dennis Au-Yeung
    email: 217013622@stu.vtc.edu.hk
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://BScCOM-Blog-API-example.wongazta.repl.co'
    description: Development server
tags:
  - name: Users
    description: API endpoints for user management.
  - name: Breeds
    description: Access and view breeds of the dog
  - name: Dogs
    description: API endpoints for dog management.
  - name: Favourites
    description: API endpoints for favourites view and like/unlike.
  - name: Comments
    description: API endpoints for guest and staff comment for the dog.
paths:
  /companies:
    $ref: "./companies.yaml"
  /companies/{id}:
    $ref: "./company.yaml"
  /users:
    $ref: "./users.yaml"
  /users/{id}:
    $ref: "./user.yaml"
  /users/profile:
    $ref: "./profile.yaml"
  /users/connect/{id}:
    $ref: "./userGoogle.yaml"    
  /users/p/{id}:
    $ref: "./userPwd.yaml" 
  /breeds:
    $ref: "./breeds.yaml"
  /breeds/{id}:
    $ref: "./breed.yaml"
  /dogs:
    $ref: "./dogs.yaml"
  /dogs/{id}:
    $ref: "./dog.yaml"
  /dogs/image/{id}:
    $ref: "./dogImage.yaml"
  /favourites:
    $ref: "./favourites.yaml"
  /favourites/{dogId}/{isFavourite}:
    $ref: "./favourite.yaml"
  /comments/{dogId}:
    $ref: "./comments.yaml"
  /comments/:
    $ref: "./comment.yaml"
