openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple blog API.
  contact:
    name: Dennis Au-Yeung
    email: 217013622@stu.vtc.edu.hk
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://BScCOM-Blog-API-example.wongazta.repl.co'
    description: Development server
tags:
  - name: Companies
    description: API endpoints for company management
  - name: Users
    description: API endpoints for user management.
  - name: Breeds
    description: Access and view breeds of the dog
  - name: Dogs
    description: API endpoints for dog management.
paths:
  /companies:
    $ref: "./companies.yaml"
  /companies/{id}:
    $ref: "./company.yaml"
  /users:
    $ref: "./users.yaml"
  /users/{id}:
    $ref: "./user.yaml"
  /breeds:
    $ref: "./breeds.yaml"
  /breeds/{id}:
    $ref: "./breed.yaml"
  /dogs:
    $ref: "./dogs.yaml"
  /dogs/{id}:
    $ref: "./dog.yaml"
